server:
  port: 9095

management:
  endpoint:
    configprops:
      show-values: ALWAYS
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
      path-mapping:
        health: prodHealthCheck
      base-path: /prodAdmin
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5,0.9, 0.99
      percentiles-histogram:
        http:
          server:
            requests: true


students:
  list:
    - id: 1
      name: Manoj
      course: Spring boot microservices
      email: manoj@gmail.com
    - id: 2
      name: Rohit
      course: JavaScript
      email: dinesh@gmail.com
    - id: 3
      name: Madhukar
      course: React
      email: sharat@gmail.com
